---
title: "Figure 4"
author: "lauryn davis"
date: "6/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(googlesheets4)
library(ggrepel)
library(showtext)
library(extrafont)
library(grid)
library(magick)
```
```{r}
font_files() %>% tibble() %>% filter(str_detect(family, "Playfair")) %>% pull(file)
names(pdfFonts())

font_add(family = "Rokkitt1", regular = "Rokkitt-SemiBold.ttf")
font_add(family = "Rokkitt", regular = "Rokkitt-Regular.ttf")
font_add(family = "playfair", regular = "PlayfairDisplay-MediumItalic.ttf")

font_add_google(name = "Barlow Condensed", family = "Circle")
showtext_auto()

picture <- image_graph(width = 570, height = 870)
annotation_custom2 <- 
function (grob, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax =Inf, data) 
{
  layer(data = data, stat = StatIdentity, position = PositionIdentity, 
        geom = ggplot2:::GeomCustomAnn, 
        inherit.aes = TRUE, params = list(grob = grob, 
                                          xmin = xmin, xmax = xmax, 
                                          ymin = ymin, ymax = ymax))
}
ggplot() + theme_void()
dev.off()
img <- image_draw(picture)
 
 polygon(c(30.7, 538, 550, 19.1), c(850, 850, 840, 840), border = "black", col = "#d69083")+
   polygon(c(19.1, 550, 552, 16), c(840, 840, 830, 830), border = "black", col = "#d69083")+
   polygon(c(16, 552, 561, 10), c(830, 830, 820, 820), border = "black", col = "#d69083")+
   polygon(c(10, 561, 570, 1.7), c(820, 820, 810, 810), border = "black", col = "#d69083")+
   polygon(c(1.7, 570, 560, 10), c(810, 810, 800, 800), border = "black", col = "#d69083")+
   polygon(c(10, 560, 473, 101), c(800, 800, 790, 790), border = "black", col = "#d69083")+
   polygon(c(101, 473, 399, 169), c(790, 790, 780, 780), border = "black", col = "#d69083")+
   polygon(c(169, 399, 340, 230), c(780, 780, 770, 770), border = "black", col = "#d69083")+
   polygon(c(230, 340, 294, 276), c(770, 770, 760, 760), border = "black", col = "#d69083")+
   polygon(c(276, 294, 291, 278), c(760, 760, 750, 750), border = "black", col = "#d69083")+
   polygon(c(278, 291, 289.5, 279), c(750, 750, 740, 740), border = "black", col = "#d69083")+
    polygon(c(279, 289.5, 288, 280), c(740, 740, 730, 730), border = "black", col = "#d69083")+
   polygon(c(280, 288, 287, 280.6), c(730, 730, 720, 720), border = "black", col = "#d69083")+
   polygon(c(280.6, 287, 286, 281), c(720, 720, 710, 710), border = "black", col = "#d69083")+
   polygon(c(281, 286, 289, 279), c(710, 710, 700, 700), border = "black", col = "#d69083")+
   polygon(c(279, 289, 290, 277), c(700, 700, 690, 690), border = "black", col = "#d69083")+
   polygon(c(277, 290, 290, 277), c(690, 690, 680, 680), border = "black", col = "#d69083")+
   polygon(c(277, 290, 290, 276), c(680, 680, 670, 670), border = "black", col = "#d69083")+
   polygon(c(276, 290, 290, 276), c(670, 670, 660, 660), border = "black", col = "#d69083")+
   polygon(c(276, 290, 290, 276), c(660, 660, 650, 650), border = "black", col = "#d69083")+
    polygon(c(276, 290, 289, 277), c(650, 650, 640, 640), border = "black", col = "#d69083")+
   polygon(c(277, 289, 288, 278.5), c(640, 640, 630, 630), border = "black", col = "#d69083")+
   polygon(c(278.5, 288, 287, 279), c(630, 630, 620, 620), border = "black", col = "#d69083")+
   polygon(c(279, 287, 284, 282), c(620, 620, 610, 610), border = "black", col = "#d69083")+
   polygon(c(282, 284, 285, 281), c(610, 610, 600, 600), border = "black", col = "#d69083")+
   polygon(c(281, 285, 285.5, 280), c(600, 600, 590, 590), border = "black", col = "#d69083")+
   polygon(c(280, 285.5, 286, 279), c(590, 590, 580, 580), border = "black", col = "#d69083")+
    polygon(c(279, 286, 284, 281), c(580, 580, 570, 570), border = "black", col = "#d69083")+
   polygon(c(281, 284, 283.5, 281.5), c(570, 570, 560, 560), border = "black", col = "#d69083")+
    polygon(c(281.5, 283.5, 282, 282), c(560, 560, 550, 550), border = "black", col = "#d69083")+
   polygon(c(282, 282, 282, 282), c(550, 550, 540, 540), border = "black", col = "#d69083")+
   polygon(c(282, 282, 283, 281), c(540, 540, 530, 530), border = "black", col = "#d69083")+
    polygon(c(281, 283, 282, 282), c(530, 530, 520, 520), border = "black", col = "#d69083")+
   polygon(c(282, 282, 282, 282), c(520, 520, 510, 510), border = "black", col = "#d69083")+
    polygon(c(282, 282, 282, 282), c(510, 510, 500, 500), border = "black", col = "#d69083")+
   polygon(c(282, 282, 283, 281), c(500, 500, 490, 490), border = "black", col = "#d69083")+
   polygon(c(281, 283, 285, 279), c(490, 490, 480, 480), border = "black", col = "#d69083")+
   polygon(c(279, 285, 286, 278), c(480, 480, 470, 470), border = "black", col = "#d69083")+
    polygon(c(278, 286, 287, 277), c(470, 470, 460, 460), border = "black", col = "#d69083")+
   polygon(c(277, 287, 288, 275), c(460, 460, 450, 450), border = "black", col = "#d69083")+
    polygon(c(275, 288, 289, 273), c(450, 450, 440, 440), border = "black", col = "#d69083")+
   polygon(c(273, 289, 289, 273), c(440, 440, 430, 430), border = "black", col = "#d69083")+
   polygon(c(273, 289, 289, 273), c(430, 430, 420, 420), border = "black", col = "#d69083")+
   polygon(c(273, 289, 289, 273), c(420, 420, 410, 410), border = "black", col = "#d69083")+
   polygon(c(273, 289, 289, 273), c(410, 410, 400, 400), border = "black", col = "#d69083")+
   polygon(c(273, 289, 291, 272), c(400, 400, 390, 390), border = "black", col = "#d69083")+
   polygon(c(272, 291, 291, 272), c(390, 390,380, 380), border = "black", col = "#d69083")+
   polygon(c(272, 291, 291, 272), c(380, 380, 370, 370), border = "black", col = "#d69083")+
   polygon(c(272, 291, 291, 272), c(370, 370, 360, 360), border = "black", col = "#d69083")+
   polygon(c(272, 291, 291, 272), c(360, 360, 350, 350), border = "black", col = "#d69083")+
   polygon(c(272, 291, 291, 272), c(350, 350, 340, 340), border = "black", col = "#d69083")+
   polygon(c(272, 291, 292, 270), c(340, 340, 330, 330), border = "black", col = "#d69083")+
   polygon(c(270, 292, 293, 269), c(330, 330, 320, 320), border = "black", col = "#d69083")+
   polygon(c(269, 293, 292, 270), c(320, 320, 310, 310), border = "black", col = "#d69083")+
   polygon(c(270, 292, 290, 271), c(310, 310, 300, 300), border = "black", col = "#d69083")+
   polygon(c(271, 290, 288, 272), c(300, 300, 290, 290), border = "black", col = "#d69083")+
    polygon(c(272, 288, 286, 275), c(290, 290, 280, 280), border = "black", col = "#d69083")+
   polygon(c(275, 286, 284, 277), c(280, 280, 270, 270), border = "black", col = "#d69083")+
   polygon(c(277, 284, 285, 276), c(270, 270, 260, 260), border = "black", col = "#d69083")+
   polygon(c(276, 285, 285, 276), c(260, 260, 250, 250), border = "black", col = "#d69083")+
   polygon(c(276, 285, 285, 276), c(250, 250, 240, 240), border = "black", col = "#d69083")+
   polygon(c(276, 285, 285, 276), c(240, 240, 230, 230), border = "black", col = "#d69083")+
   polygon(c(276, 285, 288, 273), c(230, 230, 220, 220), border = "black", col = "#d69083")+
   polygon(c(273, 288, 288, 273), c(220, 220, 210, 210), border = "black", col = "#d69083")+
   polygon(c(273, 288, 290, 270), c(210, 210, 200, 200), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(200, 200, 190, 190), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(190, 190, 180, 180), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(180, 180, 170, 170), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(170, 170, 160, 160), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(160, 160, 150, 150), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(150, 150, 140, 140), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(140, 140, 130, 130), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(130, 130, 120, 120), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(130, 130, 120, 120), border = "black", col = "#d69083")+
   polygon(c(270, 290, 289, 270), c(120, 120, 110, 110), border = "black", col = "#d69083")+
   polygon(c(270, 289, 289, 270), c(110, 110, 100, 100), border = "black", col = "#d69083")+
    polygon(c(270, 289, 289, 270), c(100, 100, 90, 90), border = "black", col = "#d69083")+
    polygon(c(270, 289, 289, 271), c(90, 90, 80, 80), border = "black", col = "#d69083")+
   polygon(c(271, 289, 289, 271), c(80, 80, 70, 70), border = "black", col = "#d69083")+
   polygon(c(271, 289, 288, 272), c(70, 70, 60, 60), border = "black", col = "#d69083")+
  
   
   text(45,851, substitute(bold("1870")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(520,851, substitute(bold("2480.7")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(34,841, substitute(bold("1869")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(528,841, substitute(bold("2588.5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(32,831, substitute(bold("1868")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(535,831, substitute(bold("2611.7")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(28,821, substitute(bold("1867")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(540,821, substitute(bold("2678.1")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(24,811, substitute(bold("1866")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(550,811, substitute(bold("2773.2")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(34,801, substitute(bold("1865")), cex = 1, col = "black", family = 'Rokkitt1')+
    
   text(520,801, substitute(bold("2680.6")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(65,789, substitute(bold("1864")), cex = 1, col = "black", family = 'Rokkitt1')+
    
   text(487,788, substitute(bold("1815.8")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(150,778, substitute(bold("1863")), cex = 1, col = "black", family = 'Rokkitt1')+
     
   text(424,778, substitute(bold("1119.8")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(201,770, substitute(bold("1862")), cex = 1, col = "black", family = 'Rokkitt1')+
    
   text(382,770, substitute(bold("524.2")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(253,760, substitute(bold("1861")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,758, substitute(bold("90.  6")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,750, substitute(bold("1860")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,748, substitute(bold("64.  8")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,740, substitute(bold("1859")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,738, substitute(bold("58.  5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,730, substitute(bold("1858")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,728, substitute(bold("44.  9")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,720, substitute(bold("1857")), cex = 1, col = "black", family = 'Rokkitt1')+
    
   text(312,718, substitute(bold("28.  7")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,710, substitute(bold("1856")), cex = 1, col = "black", family = 'Rokkitt1')+
     
   text(312,708, substitute(bold("32.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,700, substitute(bold("1855")), cex = 1, col = "black", family = 'Rokkitt1')+
     
   text(312,698, substitute(bold("35.  6")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,690, substitute(bold("1854")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,688, substitute(bold("42.  2")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,680, substitute(bold("1853")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,678, substitute(bold("59.  8")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   
   text(255,670, substitute(bold("1852")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,668, substitute(bold("66.  2")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,660, substitute(bold("1851")), cex = 1, col = "black", family = 'Rokkitt1')+
    
   text(312,658, substitute(bold("68.  3")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   
    text(255,650, substitute(bold("1850")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,648, substitute(bold("63.  5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,640, substitute(bold("1849")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,638, substitute(bold("63.  1")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,630, substitute(bold("1848")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,628, substitute(bold("47.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,620, substitute(bold("1847")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,618, substitute(bold("38.  8")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,610, substitute(bold("1846")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,608, substitute(bold("15.  6")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,600, substitute(bold("1845")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,598, substitute(bold("15.  9")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,590, substitute(bold("1844")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,588, substitute(bold("23.  5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(238,581, substitute(bold("July 1. 1843")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,578, substitute(bold("32.  7")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,570, substitute(bold("1842")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,568, substitute(bold("20.  6")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,560, substitute(bold("1841")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,558, substitute(bold("13.  6")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,550, substitute(bold("1840")), cex = 1, col = "black", family = 'Rokkitt1')+
   text(312,548, substitute(bold("5.  3")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,540, substitute(bold("1839")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,538, substitute(bold("3.  6")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,530, substitute(bold("1838")), cex = 1, col = "black", family = 'Rokkitt1')+
   
     text(312,528, substitute(bold("10.  4")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,520, substitute(bold("1837")), cex = 1, col = "black", family = 'Rokkitt1')+
   
     text(312,518, substitute(bold("3.  3")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,510, substitute(bold("1836")), cex = 1, col = "black", family = 'Rokkitt1')+
    
     text(312,508, substitute(bold("0.  3")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,500, substitute(bold("1835")), cex = 1, col = "black", family = 'Rokkitt1')+
    
     text(312,498, substitute(bold("0.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
    text(255,490, substitute(bold("1834")), cex = 1, col = "black", family = 'Rokkitt1')+
    
     text(312,488, substitute(bold("4.  8")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,480, substitute(bold("1833")), cex = 1, col = "black", family = 'Rokkitt1')+
    
     text(312,478, substitute(bold("7.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,470, substitute(bold("1832")), cex = 1, col = "black", family = 'Rokkitt1')+
   
     text(312,468, substitute(bold("24.  3")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,460, substitute(bold("1831")), cex = 1, col = "black", family = 'Rokkitt1')+
      
     text(312,458, substitute(bold("39.  1")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,450, substitute(bold("1830")), cex = 1, col = "black", family = 'Rokkitt1')+
    
     text(312,448, substitute(bold("48.  6")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,440, substitute(bold("1829")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,438, substitute(bold("58.  4")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,430, substitute(bold("1828")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,428, substitute(bold("67.  5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,420, substitute(bold("1827")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,418, substitute(bold("74.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,410, substitute(bold("1826")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,408, substitute(bold("81.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,400, substitute(bold("1825")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,398, substitute(bold("83.  8")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,390, substitute(bold("1824")), cex = 1, col = "black", family = 'Rokkitt1')+
    
    text(312,388, substitute(bold("90.  3")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,380, substitute(bold("1823")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,378, substitute(bold("90.  9")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,370, substitute(bold("1822")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,368, substitute(bold("93.  5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,360, substitute(bold("1821")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,358, substitute(bold("90.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,350, substitute(bold("1820")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,348, substitute(bold("91.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,340, substitute(bold("1819")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,338, substitute(bold("95.  5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,330, substitute(bold("1818")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,328, substitute(bold("103.  5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,320, substitute(bold("1817")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,318, substitute(bold("123.  5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,310, substitute(bold("1816")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,308, substitute(bold("127.  3")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,300, substitute(bold("1815")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,298, substitute(bold("99.  8")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,290, substitute(bold("1814")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,288, substitute(bold("81.  5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,280, substitute(bold("1813")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,278, substitute(bold("56.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,270, substitute(bold("1812")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,268, substitute(bold("45.  2")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,260, substitute(bold("1811")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,258, substitute(bold("48.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,250, substitute(bold("1810")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,248, substitute(bold("53.  2")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   
   
    text(312,238, substitute(bold("57.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   
   
    text(312,228, substitute(bold("65.  2")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,240, substitute(bold("1809")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,218, substitute(bold("69.  2")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,230, substitute(bold("1808")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,208, substitute(bold("75.  7")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,220, substitute(bold("1807")), cex = 1, col = "black", family = 'Rokkitt1')+
    
    text(312,198, substitute(bold("82.  3")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,210, substitute(bold("1806")), cex = 1, col = "black", family = 'Rokkitt1')+
    
    text(312,188, substitute(bold("86.  4")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,200, substitute(bold("1805")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,178, substitute(bold("77.  1")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,190, substitute(bold("1804")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,168, substitute(bold("80.  7")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,180, substitute(bold("1803")), cex = 1, col = "black", family = 'Rokkitt1')+
   
     text(312,158, substitute(bold("83.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
   text(312,148, substitute(bold("83.  0")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,170, substitute(bold("1802")), cex = 1, col = "black", family = 'Rokkitt1')+
   
     text(312,138, substitute(bold("78.  4")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,160, substitute(bold("1801")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,128, substitute(bold("79.  2")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,150, substitute(bold("1800")), cex = 1, col = "black", family = 'Rokkitt1')+
    
    text(312,118, substitute(bold("82.  1")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,140, substitute(bold("1799")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,108, substitute(bold("83.  8")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,130, substitute(bold("1798")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,98, substitute(bold("80.  7")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,120, substitute(bold("1797")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,88, substitute(bold("78.  4")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,110, substitute(bold("1796")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,78, substitute(bold("80.  4")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,100, substitute(bold("1795")), cex = 1, col = "black", family = 'Rokkitt1')+
   
    text(312,68, substitute(bold("77.  2")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,90, substitute(bold("1794")), cex = 1, col = "black", family = 'Rokkitt1')+
   
   text(312,58, substitute(bold("75.  5")), cex = 1, col = "black", family = 'Rokkitt1')+
 
   text(255,80, substitute(bold("1793")), cex = 1, col = "black", family = 'Rokkitt1')+
   text(255,70, substitute(bold("1792")), cex = 1, col = "black", family = 'Rokkitt1')+
   text(241,60, substitute(bold("Jan 1. 1791")), cex = 1, col = "black", family = 'Rokkitt1')
   

  
dev.off()
image_write(img, path = here::here('Walker Francis', "save3.png"), format = "png")



```