```{r}
library(tidyverse)
library(showtext)
library(readxl)
library(ggpubr)
library(magick)
library(showtext)
library(extrafont)
library(grid)
```
```{r}
font_files() %>% tibble() %>% filter(str_detect(family, "Playfair")) %>% pull(file)
names(pdfFonts())

font_add(family = "Rokkitt1", regular = "Rokkitt-SemiBold.ttf")
font_add(family = "Rokkitt", regular = "Rokkitt-Regular.ttf")
font_add(family = "playfair", regular = "PlayfairDisplay-MediumItalic.ttf")

font_add_google(name = "Barlow Condensed", family = "Circle")
showtext_auto()

```

```{r}
background<- image_read(here::here('Walker Francis', "white.png"))
plot1<- image_read(here::here('Walker Francis', "save.png"))
plot2 <- image_read(here::here('Walker Francis', "save1.png"))
plot3 <- image_read(here::here('Walker Francis', "save3.png"))

img<- image_draw(background)


 dev.off()


```

```{r}

picture <- image_graph(width = 1650, height = 950)
annotation_custom2 <- 
function (grob, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax =Inf, data) 
{
  layer(data = data, stat = StatIdentity, position = PositionIdentity, 
        geom = ggplot2:::GeomCustomAnn, 
        inherit.aes = TRUE, params = list(grob = grob, 
                                          xmin = xmin, xmax = xmax, 
                                          ymin = ymin, ymax = ymax))
}

ggplot()+theme_void()
    
dev.off()
img <- image_draw(picture)

grid.raster(plot1, .19, .40, height =.74)

grid.raster(plot3, .525, .42, height = .74)
grid.raster(plot2, .84, .40, height = .74)
text(330,215, substitute(bold("1.- REVENUE.")), cex = 1.3, col = "black", family = 'Rokkitt1')
text(1385,215, substitute(bold("3.- EXPENDITURES.")), cex = 1.3, col = "black", family = 'Rokkitt1')+
  text(860,210, substitute(bold("2.- PUBLIC DEBT.")), cex = 1.3, col = "black", family = 'Rokkitt1')+
  text(1115,226, substitute(bold("In millions and tenths")), cex = .7, col = "black", family = 'playfair')+
  text(1115,236, substitute(bold("(00,000 omitted)")), cex = .7, col = "black", family = 'playfair')+
  
  text(860,224, substitute(bold("In millions and tenths")), cex = .7, col = "black", family = 'playfair')+
  text(860,234, substitute(bold("(00,000 omitted)")), cex = .7, col = "black", family = 'playfair')+
  
  text(607,226, substitute(bold("In millions and tenths")), cex = .7, col = "black", family = 'playfair')+
  text(607,236, substitute(bold("(00,000 omitted)")), cex = .7, col = "black", family = 'playfair')+
  
  text(860,35, substitute(bold("FISCAL CHART")), cex = 2, col = "black", family = 'Rokkitt1')+
  text(860,52, substitute(bold("OF THE UNITED STATES")), cex = 1.5, col = "black", family = 'Rokkitt1')+
  text(860,67, substitute(bold("SHOWING THE COURSE OF THE PUBLIC DEBT BY YEARS 1789 TO 1870.")), cex = 1, col = "black", family = 'Rokkitt')+
  text(860,77, substitute(bold("TOGETHER WITH THE PROPORTION OF THE TOTAL")), cex = 1, col = "black", family = 'Rokkitt')+
  text(860,91, substitute(bold("RECIEPTS")), cex = 1.5, col = "black", family = 'Rokkitt1')+
   text(860,104, substitute(bold("FROM EACH PRINCIPLE SOURCE OF REVENUE")), cex = 1, col = "black", family = 'Rokkitt')+
  text(860,114, substitute(bold("AND PROPORTION OF THE TOTAL")), cex = 1, col = "black", family = 'Rokkitt')+
  text(860,128, substitute(bold("EXPENDITURES")), cex = 1.5, col = "black", family = 'Rokkitt1')+
  text(860,143, substitute(bold("FOR EACH PRINCIPLE DEPARTMENT OF THE")), cex = 1, col = "black", family = 'Rokkitt')+
  text(860,153, substitute(bold("PUBLIC SERVICE.")), cex = 1, col = "black", family = 'Rokkitt')+
  text(860,163, substitute(bold("Compiled from the Report of the Secretary of the Treasury for the year 1872,")), cex = .9, col = "black", family = 'Rokkitt')+
  text(860,173, substitute(bold("BY")), cex = .75, col = "black", family = 'Rokkitt')+
  text(860,183, substitute(bold("FRANCIS A. WALKER")), cex = 1.1, col = "black", family = 'Rokkitt')+
  
  text(330,915, substitute(bold("*Fiscal Year ending June 30.")), cex = 1.1, col = "black", family = 'Rokkitt')+ 
  text(860,915, substitute(bold("The Public Debt. January. 1. 1835, was $ 37.513.")), cex = 1.1, col = "black", family = 'Rokkitt')+ 
  text(1385,915, substitute(bold("*Fiscal Year ending June 30.")), cex = 1.1, col = "black", family = 'Rokkitt')+ 
  
  segments(x0=830, x1=895, y0=197, y1=197, lwd = 1, lty = "solid")+
  
  polygon(c(90,115, 115, 90), c(40, 40, 53, 53), border = "black", col = "#c0c3b7")+
  text(171,45, substitute(bold("From Public Lands")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(90,115, 115, 90), c(65, 65, 78, 78), border = "black", col ="#b2a961")+
  text(171,70, substitute(bold("-    Bank Stock")), cex = .9, col = "black", family = 'playfair')+
   polygon(c(90,115, 115, 90), c(90, 90, 103, 103), border = "black", col ="#fedcc6")+
  text(171,95, substitute(bold("          -    Internal Revenue")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(90,115, 115, 90), c(115, 115, 128, 128), border = "black", col ="#ffe383")+
  text(164,120, substitute(bold("-    Customs")), cex = .9, col = "black", family = 'playfair')+
   polygon(c(90,115, 115, 90), c(140, 140, 153, 153), border = "black", col ="#a48048")+
  text(164,145, substitute(bold("    -    Direct Tax")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(90,115, 115, 90), c(165, 165, 178, 178), border = "black", col ='#e19d91')+
  text(162,170, substitute(bold("-    Postage")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(90,115, 115, 90), c(190, 190, 203, 203), border = "black", col ='#737165')+
  text(162,195, substitute(bold("           -    Miscellaneous")), cex = .9, col = "black", family = 'playfair')+
  
   polygon(c(1500,1525, 1525, 1500), c(10, 10, 23, 23), border = "black", col = "#ddd9cb")+
  text(1550,18, substitute(bold("Army")), cex = .9, col = "black", family = 'playfair')+
   polygon(c(1500,1525, 1525, 1500), c(30, 30, 43, 43), border = "black", col = "#a1aba6")+
  text(1550,36, substitute(bold("Navy")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(1500,1525, 1525, 1500), c(50, 50, 63, 63), border = "black", col = "#886a6d")+
  text(1555,54, substitute(bold("  Pensions")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(1500,1525, 1525, 1500), c(70, 70, 83,83), border = "black", col = "#eac85c")+
  text(1549,75, substitute(bold("Civil")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(1500,1525, 1525, 1500), c(90, 90, 103, 103), border = "black", col = "#d69083")+
  text(1554,95, substitute(bold("Indians")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(1500,1525, 1525, 1500), c(110, 110, 123, 123), border = "black", col = "#fee6a9")+
   text(1569,135, substitute(bold("Miscellaneous")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(1500,1525, 1525, 1500), c(130, 130, 143, 143), border = "black", col = "#787734")+
  text(1554,116, substitute(bold("Foreign")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(1500,1525, 1525, 1500), c(150, 150, 163, 163), border = "black", col = "#292323")+
  text(1592,155, substitute(bold("Premium on Pub. Debt.")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(1500,1525, 1525, 1500), c(170, 170, 183, 183), border = "black", col = "#777367")+
  text(1591,175, substitute(bold("Principal of Pub. Debt.")), cex = .9, col = "black", family = 'playfair')+
  polygon(c(1500,1525, 1525, 1500), c(190, 190, 203, 203), border = "black", col = "#aea596")+
  text(1589,195, substitute(bold("Interest on Pub. Debt.")), cex = .9, col = "black", family = 'playfair')


dev.off()
image_write(img, path = here::here('Walker Francis', "final.png"), format = "png")

```